version: '3.8'

services:
  app:
    image: goddam1110/sns-app:latest
    ports:
      - "8081:8081"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/log:/var/log
    restart: always